_translation_edit_in_place:
    resource: '@TranslationBundle/Resources/config/routing_edit_in_place.yml'
    prefix:  /bolt

translation_index:
    path: /bolt/trans/{configName}
    methods: [GET]
    defaults:  { _controller: Translation\Bundle\Controller\WebUIController::indexAction, configName: null }

translation_show:
    path: /bolt/trans/{configName}/{locale}/{domain}
    methods: [GET]
    defaults:  { _controller: Translation\Bundle\Controller\WebUIController::showAction }

translation_create:
    path: /bolt/trans/{configName}/{locale}/{domain}/new
    methods: [POST]
    defaults:  { _controller: Translation\Bundle\Controller\WebUIController::createAction }

translation_edit:
    path: /bolt/trans/{configName}/{locale}/{domain}
    methods: [POST]
    defaults:  { _controller: Translation\Bundle\Controller\WebUIController::editAction }

translation_delete:
    path: /bolt/trans/{configName}/{locale}/{domain}
    methods: [DELETE]
    defaults:  { _controller: Translation\Bundle\Controller\WebUIController::deleteAction }
